config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root 'pages#home'

  resources :users, except: [:new, :edit]

  scope "/start" do
    get "/", to: "pages#start", as: "start"
    post "/", to: "pages#start_user"
    get "/:username", to: "pages#in_or_up", as: "in_or_up"
  end

  scope "/dashboard" do
    get "/", to: "pages#dashboard"    
    resources :bookmarks
    resources :notes
    resources :lists
  end

  post "signin", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  validates_presence_of :title, :description, :url
  belongs_to :user
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list
  validates :content,
    presence: true
end

app/models/list.rb
class List < ApplicationRecord
  has_many :items
  belongs_to :user
  validates :title,
    presence: true

  accepts_nested_attributes_for :items, allow_destroy: true
end

app/models/note.rb
class Note < ApplicationRecord
  validates_presence_of :title, :description
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.username = username.downcase }
  has_secure_password
  has_many :bookmarks
  has_many :notes
  has_many :lists

  validates :username, 
    presence: true, 
    uniqueness: { case_sensitive: false }, 
    length: { minimum: 3, maximum: 25 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  layout 'dashboard'
  before_action :redirect_unauthenticated

  def index
    user = User.find(session[:user_id])
    @bookmarks = user.bookmarks
  end

  def show
    user = User.find(session[:user_id])
    @bookmark = user.bookmarks.find(params[:id])
  end

  def new 
    user = User.find(session[:user_id])
    @bookmark = user.bookmarks.build
  end

  def create
    user = User.find(session[:user_id])
    @bookmark = user.bookmarks.build(bookmark_params)
    if @bookmark.save
      flash[:notice] = "Bookmark was created successfully"
      redirect_to @bookmark
    else 
      render :new, status: :unprocessable_entity
    end
  end


  def edit
    user = User.find(session[:user_id])
    @bookmark = user.bookmarks.find(params[:id])
  end

  def update
    user = User.find(session[:user_id])
    @bookmark = user.bookmarks.find(params[:id])

    if @bookmark.update(bookmark_params);
      flash[:notice] = "Bookmark was updated successfully"
      redirect_to @bookmark
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy 
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    redirect_to bookmarks_path, status: :see_other
  end

  private
    def bookmark_params
      params.require(:bookmark).permit(:title, :description, :url)
    end
    
    def redirect_unauthenticated
      redirect_to start_path unless session[:user_id]
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  layout 'dashboard'
  before_action :redirect_unauthenticated
  
  def index
    user = User.find(session[:user_id])
    @lists = user.lists
  end

  def show
    user = User.find(session[:user_id])
    @lists = user.lists
  end

  def new
    @list = List.new
    @list.items.build
  end

  def create
    user = User.find(session[:user_id])
    @list = user.lists.new(list_params)

    if user.save       
      flash[:notice] = "List saved"
      redirect_to @list
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    if @list.update(list_params)
      flash[:notice] = "List was updated succesfuly"
      redirect_to @list
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
  end

  private
    def redirect_unauthenticated
      redirect_to start_path unless session[:user_id]
    end

    def list_params
      params.require(:list).permit(:title, items_attributes: [:id, :content, :_destroy])
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  layout 'dashboard'
  before_action :redirect_unauthenticated
  
  def index
    user = User.find(session[:user_id])
    @notes = user.notes
  end

  def show
    user = User.find(session[:user_id])
    @note = user.notes.find(params[:id])
  end

  def new
    user = User.find(session[:user_id])
    @note = user.notes.build
  end

  def create
    user = User.find(session[:user_id])
    @note = user.notes.build(note_params)

    if user.save
      flash[:notice] = "Note saved correctly"
      redirect_to @note
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    user = User.find(session[:user_id])
    @note = user.notes.find(params[:id])
  end

  def update
    user = User.find(session[:user_id])
    @note = user.notes.find(params[:id])

    if @note.update(note_params)
      flash[:notice] = "Note updated correctly"
      redirect_to @note
    else
      flash.now[:alert] = "Unable to update note"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    user = User.find(session[:user_id])
    note = user.notes.find(params[:id])

    note.destroy

    redirect_to notes_path, status: :see_other
  end

  private
    def note_params
      params.require(:note).permit(:title, :description)
    end
    
    def redirect_unauthenticated
      redirect_to start_path unless session[:user_id]
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  layout 'pages'
  
  def home
  end

  def start
  end

  def start_user
    redirect_to in_or_up_path(user_params[:username])
  end

  def in_or_up
    @user = User.find_by(username: params[:username]) 
    @requested_username = params[:username]
  end

  def dashboard
    redirect_to start_path unless session[:user_id] # Why I cannot access application helper: current_user?
  end

  private
    def user_params
      params.require(:user).permit([:username])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to user_path(session[:user_id]) if session[:user_id] 
  end

  def create
    @session = session_params
    username = @session[:username].downcase
    @user = User.find_by(username: username)
    @requested_username = username
    
    if @user && @user.authenticate(session_params[:password])
      flash[:notice] = "Logged in successfully"
      session[:user_id] = @user.id
      redirect_to :root
    else
      flash.now[:alert] = "Your login details were incorrect"
      render 'pages/in_or_up', status: :unprocessable_entity, layout: 'pages'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out successfully"
    redirect_to signin_path, status: :see_other
  end

  private
    def session_params
      params.require(:session).permit(:username, :password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :set_user -> Remove possible redundacy 
  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_param)
    if @user.save
     session[:user_id] = @user.id
     flash[:notice] = "Hello #{@user.username}, welcome to Tachuela"
     redirect_to :root 
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @user = User.find(params[:id])
  end 

  private
    def user_param 
      params.require(:user).permit(:username, :password)
    end
end 

app/helpers/application_helper.rb
module ApplicationHelper
  def signed_in?
    !!current_user
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/views/bookmarks/_form.html.haml
= render "shared/errors", obj: bookmark
= form_with(model: bookmark, local: true) do |form|
  = form.label :title
  = form.text_field :title
  = form.label :url
  = form.text_field :url
  = form.label :description
  = form.text_field :description
  = form.submit

app/views/bookmarks/edit.html.haml
%h1 Edit bookmark
= render "form", bookmark: @bookmark

app/views/bookmarks/index.html.haml
%section.top
  %h2 Your bookmarks
  = link_to "Create +", new_bookmark_path
- @bookmarks.each do |bookmark|
  %details
    %summary=bookmark.title
    %div
      %p= bookmark.url
      %p=bookmark.description
      %p #{link_to "Edit", edit_bookmark_path(bookmark) } | #{link_to "Delete", bookmark_path(bookmark), data: { confirm: "Are you sure", turbo_method: "delete"}}

app/views/bookmarks/new.html.haml
%h1 Create new bookmark
= render "form", bookmark: @bookmark

app/views/bookmarks/show.html.haml
%h1 Bookmark ##{@bookmark.id}
%h2=@bookmark.title
%p=@bookmark.url
%p=@bookmark.description
%div
  = link_to "Edit", edit_bookmark_path(@bookmark)
  |
  = link_to "Delete", bookmark_path(@bookmark), data: { confirm: "Are you sure", turbo_method: "delete" }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title TachuelaRails
    %meta{name: "vieport", content: "width=device-width,initial-scale=1"}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body
    %header
      = render 'shared/navigation'
      = render 'shared/flash'
    %main.container
      = yield

app/views/layouts/dashboard.html.haml
!!!
%html
  %head
    %title TachuelaRails
    %meta{name: "vieport", content: "width=device-width,initial-scale=1"}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "dashboard", "data-turbo-track": "reload"
    = javascript_importmap_tags
    %link{rel:"stylesheet", href:"https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css"}
  %body
    %header
      = render 'shared/flash'
      %hgroup.container
        %h1 Tachuela on Rails 📌
        = render 'shared/navigation'
      %nav
        %ul
          %li=link_to "Bookmarks", "/dashboard/bookmarks"
          %li=link_to "Notes", "/dashboard/notes"
          %li=link_to "Lists", "/dashboard/lists"
    %aside
      = render 'shared/sidebar'
    %main
      = yield

app/views/layouts/pages.html.haml
!!!
%html
  %head
    %title Tachuela Rails
    %meta{name:"viewport", content:"width=device-width,initial-scale=1"}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "pages", "data-turbo-track": "reload"
    = javascript_importmap_tags
    %link{rel:"stylesheet", href:"https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css"}
  %body
    %header
      = render 'shared/flash'
    %hgroup.container
      %h1 Tachuela on Rails 📌
      %p Create notes, lists and bookmarks
    %main.container
      = yield

app/views/lists/_form.html.haml
= render 'shared/errors', obj: list
= form_with(model: list, local: true) do |form|
  = form.label :title
  = form.text_field :title
  %p Items:
  %ul
  - list.items.each do |item|
    - if item.content
      %li=item.content
  = form.fields_for :items do |items_form|
    = items_form.label :new_item
    = items_form.text_field :content
  = form.submit

app/views/lists/edit.html.haml
%h1 Create new list
= render 'form', list: @list

app/views/lists/index.html.haml
%section.top
  %h2 Your lists
  = link_to "Create +", new_list_path
- @lists.each do |list|
  %details
    %summary
      %div
        %p=list.title
        %p #{link_to "Edit", edit_list_path(list) } | #{link_to "Delete", list_path(list), data: { confirm: "Are you sure", turbo_method: "delete"}}
    %ul
      - list.items.each do |item|
        %li=item.content

app/views/lists/new.html.haml
%h1 Create new list
= render 'form', list: @list

app/views/lists/show.html.haml
%p Your lists:
- @lists.each do |list|
  %details
    %summary
      = list.title
      |
      = link_to "Edit", edit_list_path(list)
    %ul
      - list.items.each do |item|
        %li=item.content

app/views/notes/_form.html.haml
= render 'shared/errors', obj: note
= form_with(model: note, local: true) do |form|
  = form.label :title
  = form.text_field :title
  = form.label :description
  = form.text_area :description
  = form.submit

app/views/notes/edit.html.haml
%h1 Edit note
= render 'form', note: @note

app/views/notes/index.html.haml
%section.top
  %h2 Your notes
  = link_to "Create +", new_note_path
- @notes.each do |note|
  %details
    %summary
      %span=note.title
    %blockquote=note.description
    %p #{link_to "Edit", edit_note_path(note) } | #{link_to "Delete", note_path(note), data: { confirm: "Are you sure", turbo_method: "delete"}}

app/views/notes/new.html.haml
%h1 Create new note
= render 'form', note: @note

app/views/notes/show.html.haml
%h1="#{current_user.username} note ##{@note.id}"
%h2=@note.title
%p=@note.description

app/views/pages/dashboard.html.haml
%h1 Dashboard

%aside Siderbar

%main
  %p Create...
  .actions
    %p Note 
    %p Bookmark 
    %p List

app/views/pages/home.html.haml
%p Tachuela is a personal project. Originally created to get my first developer job with Vue.js and now re-done in Rails.
%p
  You can 
  %a{href: "/start"} get started 
  and and play around or
  learn more 
  %a{href: "/about"} about it.

app/views/pages/in_or_up.html.haml
- if @user
  %p 
    Hello 
    %strong #{@user.username},
    care to tell us your password?
  = form_with scope: :session, url: signin_path do |form|
    = form.hidden_field :username, value: @requested_username
    = form.label :password 
    = form.password_field :password 
    = form.submit "Sign in" 
- else
  %p We could not find that user, enter a password to create one
  = form_with scope: :user, url: users_path do |form|
    = form.hidden_field :username, value: @requested_username 
    = form.label :password 
    = form.password_field :password 
    = form.submit "Sign up"

app/views/pages/start.html.haml
%p Have used Tachuela before? Give us your username, if not we will create a new user for you.
= form_with scope: :user, method: :post do |form|
  = form.label :username
  = form.text_field :username
  = form.submit

app/views/shared/_errors.html.haml
- if obj.errors.any?
  %h3 Error saving the #{obj.class.name.downcase}: 
  - obj.errors.full_messages.each do |message|
    %li=message

app/views/shared/_flash.html.haml
- if flash[:notice]
  %span.flash.notice="✅ #{flash[:notice]}"
- if flash[:alert]
  %span.flash.alert="❌ #{flash[:alert]}"

app/views/shared/_navigation.html.haml
- if signed_in?
  = link_to 'Log out', logout_path, data: { turbo_method: :delete }
- else
  = link_to 'Sign in', signin_path

app/views/shared/_sidebar.html.haml
%h3 Entries
%p This section will render all user entries and a search bar.